### ISSUE TITLE
Case inconsistency of addresses in contract_info that are not EVM-compatible chains

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#321]
**Describe the bug**

**To Reproduce**

```
select * from contract_info 
where chain ='Solana'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/212001693-e70afcfb-610f-4f53-a9c0-7aa4c341fa37.png)

**Comment by Rosen529** [comment]
fixed
