### ISSUE TITLE
nft_orders data Missing history data, and expired orders do not fail

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#326]
**Describe the bug**
nft_orders data Missing history data, and expired orders do not fail
**To Reproduce**
`
select * 
from nft_orders 
where 
  marketplace_slug = 'opensea' 
  and collection_contract_address = '0x23581767a106ae21c074b2276d25e5c3e136a68b' 
  and nft_token_id = '3304'
  and created_at > date('2022-12-01')
  order by created_at desc
`

**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/212024762-8c862064-789f-40fe-86a8-f0be3d060cb8.png)

**Comment by Himkid19** [comment]
we have collected moonbird historical data and fixed the issue of the expired orders, but can not collect the moonbird expired offer order completely, cause the Opensea API only provide the active orders at API
