### ISSUE TITLE
Sum is not available after joining tables

### ISSUE THREAD

**Issue by PHBever** [footprintanalytics/footprint-web#328]
[link](https://www.footprint.network/chart/Gamefi-Contract-Infos%2C-Filtered-by-Protocol-Slug-fp-36270)

After joining the data table, the summarize doesn't work, can find the sum or avg

![image](https://user-images.githubusercontent.com/121855031/212304450-00b70ecc-4b07-4408-b187-7c42ae783bd6.png)

**Comment by sefigi** [comment]
This is what happens when your first data source has no data of the numeric type

**Comment by deoooo** [comment]
Temporary workaround with "Custom Expression"
![image](https://user-images.githubusercontent.com/38069851/215419460-c4fd93a6-c684-4aec-a79c-ecfb6468b65b.png)
