### ISSUE TITLE
Click on the Cancel button after editing the dashboard and the dashboard retains the edited content.

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#330]
**Describe the bug**
Click on the Cancel button after editing the dashboard and the dashboard retains the edited content.
[link](https://www.footprint.network/@Higi/NFT-Market-Overview)
**To Reproduce**
1. edit dashboard
2. add chart
3. cancel edit 

**Screenshots**

**Comment by sefigi** [comment]
https://github.com/footprintanalytics/footprint-web/issues/333 duplicute

**Comment by ydpzg** [comment]
The bug of editing dashboard cancel has been fixed
