### ISSUE TITLE
The page often crashes

### ISSUE THREAD

**Issue by PHBever** [footprintanalytics/footprint-web#333]
Making a dashboard, the page often crashes. “Something's gone wrong" appears.
When I finished changing the parameters and clicked "done", the page crashed

![bug](https://user-images.githubusercontent.com/121855031/212618795-5b3d07dd-4b41-4bca-bfab-2318ac506d6c.gif)

**Comment by sefigi** [comment]
https://github.com/footprintanalytics/footprint-web/issues/330
