### ISSUE TITLE
duplicated gamefi projects and one project logo is empty

### ISSUE THREAD

**Issue by LynnTsang** [footprintanalytics/footprint-web#336]
https://www.footprint.network/@MetaverseHub/MetaverseHub-GameFi-Weekly-Report?date_range=2023-01-09~2023-01-15

![image](https://user-images.githubusercontent.com/121166680/212644088-7651c2a8-86c1-4c4d-bf9a-5e7349bb8fd1.png)

**Comment by sefigi** [comment]
Outer Ring MMO and  Sweat Wallet Logos are not collected, team is collecting
