### ISSUE TITLE
The event name in the polygon decoded event table is ChestOpened. There is an exception in the parsed data

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#337]
**Describe the bug**
The event name in the polygon decoded event table is ChestOpened. There is an exception in the parsed data**To Reproduce**
Using query:
```
select
    transaction_hash as tx_hash,
    block_timestamp as block_time,
    decoded_data
from "polygon_decoded_events"
where contract_address = '0x245755b57c16ec301e50d3b84fb12485f7e7860b'
and event_name = 'ChestOpened'
and transaction_hash = '0xf571c99d72d6bb8dfb8d861d7ddecf36a972742b0d5aa600076ab27205a10f83'
```
Polygon Scan:
https://polygonscan.com/tx/0xf571c99d72d6bb8dfb8d861d7ddecf36a972742b0d5aa600076ab27205a10f83
**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/212798272-dac71554-4db4-4514-a410-a8f50b8c3d56.png)
![image](https://user-images.githubusercontent.com/44665855/212798315-c8e67b2f-fc08-405f-8c0c-52a6a18e9614.png)

**Comment by alex-klg** [comment]
The recently fixed logic of decode event, event table will also be scheduled to update the historical data

**Comment by alex-klg** [comment]
polygon_decode_event history data is updated
![image](https://user-images.githubusercontent.com/93317149/215238980-88b1289d-1908-4531-a3b7-c1036674866f.png)
