### ISSUE TITLE
API return nft collection info data  sorts randomly

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#346]
**Describe the bug**
jcmlumacad ： I tried this api https://docs.footprint.network/reference/get_nft-collection-info and every time I request for collections, it sorts randomly. I only used the chain and nothing else on the metadata. why is that?
**To Reproduce**
1. it sorts randomly.
2. it is offset like a page number or something? is it like skipping the number of collections? 
3. the page size on the nft collections by chain is not updated, i tried without putting the limit, it returns 100 collections
**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/213074350-ece751c6-30ad-4929-8848-d51534f6ef03.png)

**Comment by NoKnow606** [comment]
Since it is sorted by updated_at, there is a duplicate value of updated_at which leads to random sorting, resulting in duplicate paging, it has been changed to sort by created_at + unique key by default
