### ISSUE TITLE
Era7's dashboard, there is a chart without data.

### ISSUE THREAD

**Issue by LynnTsang** [footprintanalytics/footprint-web#350]
https://www.footprint.network/@Higi/Era7-Cards-NFT-Collections?game_name=era7-game-of-truth&collection=era7-cards&series_date=past90days

![image](https://user-images.githubusercontent.com/121166680/213160984-17d8537e-18a1-474a-9491-aa46f315be68.png)

**Comment by sefigi** [comment]
This chart needs to load too much data, the network is not good to cause the page timeout, need to reduce the amount of data loaded
