### ISSUE TITLE
The data api documentation restriction is incorrectly described

### ISSUE THREAD

**Issue by RryanLH** [footprintanalytics/footprint-web#359]
The data api documentation restriction is incorrectly described
![image](https://user-images.githubusercontent.com/119930236/213658576-ed60604c-581c-4c49-b141-63fc98868cdf.png)

**Comment by sefigi** [comment]
if you look at the time, the status goes 429. it means the rate limit exceeded

**Comment by ydpzg** [comment]
We have updated the doc at this link https://www.footprint.network/pricing. Functionality is now consistent.
