### ISSUE TITLE
Lido event is incomplete in ethereum_decoded_events 

### ISSUE THREAD

**Issue by no7dw** [footprintanalytics/footprint-web#362]
**Describe the bug**
Lido event is incomplete in ethereum_decoded_events 
the  minimal timestamp should be 2020-12-18 23:32

```

select min(evt_block_time)   
FROM lido."steth_evt_Submitted" 
```

**To Reproduce**
https://www.footprint.network/chart/lido-debug-fp-36771

 
```
with det as(
select  date_trunc('day', block_timestamp) as time, 
     json_query(
                     decoded_data,
                     'lax $.amount' OMIT QUOTES
                    ) AS amount 
                    
    from "ethereum_decoded_events"
    where lower(protocol_slug) = 'lido' 
 
    and event_name = 'Submitted'
    )
select min(time)  , count(1) as cnt from det 
```

 

**Screenshots**
![image](https://user-images.githubusercontent.com/2989631/215248732-3abe2b04-4a60-4f86-be29-e5527d2d3115.png)

**Comment by alex-klg** [comment]
There are some newly included, or updated contracts, historical data is not updated in a timely manner, the events of these contracts will be scheduled to be updated

**Comment by alex-klg** [comment]
It has been replenished
![image](https://user-images.githubusercontent.com/93317149/215262728-0f318e09-f0bb-433c-8ce6-4110bdfb9e35.png)
