### ISSUE TITLE
The event name for the planet-ix protocol of the polygon_decoded_events table is RequestClaimFacility data duplication.

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#365]
**Describe the bug**

**To Reproduce**
```
select * from "polygon_decoded_events"
where contract_address ='0x9c31ada541dfa3e867460be0572c1a57311df6ff'
and transaction_hash ='0x5b372886909d131153ddd96f39fa1b2c8a71492891d6c4c708e11a27d12971bd'

```
**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/215302743-b37c9c7e-420d-4d1b-b130-e959fc508419.png)

**Comment by alex-klg** [comment]
Duplicate data has been filtered out 
![image](https://user-images.githubusercontent.com/93317149/215310048-3dfe1db2-90de-4485-9fe8-066b600186d5.png)
