### ISSUE TITLE
Bridge Dashboard miss 3 days data

### ISSUE THREAD

**Issue by PHBever** [footprintanalytics/footprint-web#366]
https://www.footprint.network/@DamonSalvatore/Bridge-Dashboard

There are 8 charts missing 3 days of data, maybe some datasets have a block.
![image](https://user-images.githubusercontent.com/121855031/215303436-660c9954-48dd-46bc-859d-b992d393098e.png)

**Comment by Jakin-Liu** [comment]
Because the system is abnormal, the missing data has been completed.

https://www.footprint.network/@DamonSalvatore/Bridge-Dashboard

From the results of this dashboard, it has returned to normal.

Thanks.
