### ISSUE TITLE
gamefi_protocol_daily_stats  data update delay 2 days

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#368]
**Describe the bug**
gamefi_protocol_daily_stats  data update delay 2 days
**To Reproduce**
https://www.footprint.network/chart/GameFi-Daily-Transactions-fp-36265
**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/215405935-09eed260-0aab-462a-be4b-3fec9113b9b9.png)

**Comment by Rosen529** [comment]
Requests to the footprint-capture-website service frequently raise exceptions, causing program interruptions. Continue to complete subsequent format operations even after a compatible exception has been raised
