### ISSUE TITLE
No link in the Discord alerts

### ISSUE THREAD

**Issue by bgodlin** [footprintanalytics/footprint-web#369]
Upon the successful emit of the alerts, they are sent to Discord without the original chart URL indication ( see https://discord.com/channels/864829036294307881/1067551874909220884/1069406669764837386 for an example), whereas the email notifications have the link included

**Comment by ydpzg** [comment]
![image](https://user-images.githubusercontent.com/2216159/217145986-4cf32b53-9c80-49a6-84d6-92c805fe0088.png)
I see that there is a corresponding chart link on the link you gave, it seems to be a problem with your discord settings.  I'll close this issue
