### ISSUE TITLE
In the dashboard, can't add the default value of a filter

### ISSUE THREAD

**Issue by PHBever** [footprintanalytics/footprint-web#374]
In the dashboard, can't add the default value of a filter. The I added a default value, it disappeared. 

https://www.footprint.network/@DamonSalvatore/Protocol-Decoded-Event?chain=Ethereum

![GIF 2023-2-1 17-33-40](https://user-images.githubusercontent.com/121855031/216007354-c78bd846-1a7f-4a75-a423-c69b50cd798b.gif)

**Comment by ydpzg** [comment]
After entering the default value, you need to press the Enter key to take effect, and it will not be saved after losing the mouse focus
