### ISSUE TITLE
Users cannot adjust the column's order when using the visualization options funtion in Dashboard

### ISSUE THREAD

**Issue by zoniguan** [footprintanalytics/footprint-web#384]
**Describe the bug**
Users cannot adjust the column's order when using the visualization options funtion in Dashboard.
When finish the drag & pull, it returns to the original position.

**To Reproduce**
1. Go to 'Any dashboard with a list chart'
2. Click on 'Visualization Options' for the chart
4. Pull & Drag the columns to adjust the order
5. It will remains the position.

**Screenshots**
![image](https://user-images.githubusercontent.com/70458964/216913169-255d28b6-b175-467f-93f1-7e279dde93a4.png)

**Comment by ydpzg** [comment]
This bug has been fixed
