### ISSUE TITLE
Users cannot use the Pivot Table, the visualiztion chart type.

### ISSUE THREAD

**Issue by zoniguan** [footprintanalytics/footprint-web#386]
**Describe the bug**
When users select the pivot table after aggregation, error shows as attached. 

**To Reproduce**
1. Go to 'any dataset' and aggregate the data
2. Click on 'Visualizaiton' and choose "Pivot Table"
3. Error shows

**Screenshots**
![image](https://user-images.githubusercontent.com/70458964/216914542-ddf7adc0-ff16-4a9d-9953-aecd77f82e36.png)

**Comment by ydpzg** [comment]
Pivot table can only be used in drag-and-drop mode, sql mode is not supported
