### ISSUE TITLE
Click on the gamefi module on the home page to jump to the protocol detail page and report an error

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#392]
**Describe the bug**
Click on the gamefi module on the home page to jump to the protocol detail page and report an error

**To Reproduce**

**Screenshots**
![2023-02-07 15 04 13](https://user-images.githubusercontent.com/44665855/217171922-033b660c-6dbc-432f-89c6-e02415da7ff0.gif)

**Comment by ydpzg** [comment]
The bug has been fixed
