### ISSUE TITLE
Hi there seems to be an error in the token_price 5mins table for WMATIC 0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270 it shoots to $2,000

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#396]
**Describe the bug**

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/217420499-c116a416-621d-4ed5-a882-46727e7c98c4.png)

**Comment by alex-klg** [comment]
The abnormal coin price of 0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270 has been fixed
