### ISSUE TITLE
Hi all! I have checked the issue with block_date and block_timestamp for blocks 16563646, 16566032 and 16570290. It seems that the endpoints NFT Transfers and NFT Transactions show data as UTC but is GMT+8. So, this issue is shifting all your data 8 hours.

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#397]
**Describe the bug**
Hi all! I have checked the issue with block_date and block_timestamp for blocks 16563646, 16566032 and 16570290. It seems that the endpoints NFT Transfers and NFT Transactions show data as UTC but is GMT+8. So, this issue is shifting all your data 8 hours.

**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/217448329-42a6f2d1-1cde-42e6-b5aa-d6f395ccbc47.png)

**Comment by NoKnow606** [comment]
The time zone was not set correctly, resulting in abnormal data, fixed
