### ISSUE TITLE
protocol_transactions which protocol_name is Ubeswap in Celo chain  seems to be a misspelling of Uniswap

### ISSUE THREAD

**Issue by penspencap** [footprintanalytics/footprint-web#406]
**Describe the bug**
```sql
select * from "protocol_transactions"
where chain = 'Celo'
    and protocol_name = 'Ubeswap'
limit 10
```
I checked out a few deals and they all look like uniswap v2

**Screenshots**
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/25994819/217783519-5f77e8a8-da77-46bb-b420-bd73f7185d29.png">

**Comment by sefigi** [comment]
Only keep the protocol data of gamefi
