### ISSUE TITLE
nft_transactions buyer data error

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#410]
We've detected a possibly issue. The following collection and specifically transaction has buyer_address as '0x0000000...' (query below). If we have a look in Etherscan we can see that the correct buyer is 0xb5E26A...E2f183BC. Could you please have a look into it? Thanks

```
 select * 
 FROM nft_transactions 
 WHERE block_date = date'2023-01-21'
 and transaction_hash = '0xdad31b821610270a05087465992974a0859705c558f322b5f60e7bd324633093'
```

https://etherscan.io/tx/0xdad31b821610270a05087465992974a0859705c558f322b5f60e7bd324633093

**Comment by Himkid19** [comment]
this type of problem has been fixed for opensea
