### ISSUE TITLE
The price of WJEWEL is stopped at 2022

### ISSUE THREAD

**Issue by PHBever** [footprintanalytics/footprint-web#411]
The price of WJEWEL is stopped at Nov,2022
The dataset is token_daliy_stats

https://www.footprint.network/chart/token-price-wjewel-fp-37392
![image](https://user-images.githubusercontent.com/121855031/218048806-77cb07f7-d9a2-4db0-aa5d-e4515e988b25.png)

**Comment by Jakin-Liu** [comment]
Due to the adjustment of the token data maintained by fp, the index production is not related correctly. We have included it and have completed the historical data. Thank you for your feedback
