### ISSUE TITLE
No display in the left menu bar after saving the ud table

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#412]
**Describe the bug**
table_name : Address_Token_Balance

save [link](https://www.footprint.network/chart/Address-Token-Balance-fp-37388)
Click Save to prompt for content ""It looks like the process is a bit long, you can manually click the button to refresh the status."
**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/218050889-c88b7299-3d22-43b3-9329-53768a9714ed.png)

**Comment by Jakin-Liu** [comment]
There is an exception in the program. The check that the table name cannot be capitalized has been passed. Please change the table name to lowercase. Thank you for your feedback
