### ISSUE TITLE
'Help' button is blocking the dragging of the right scrollbar, please optimize

### ISSUE THREAD

**Issue by PHBever** [footprintanalytics/footprint-web#417]
The 'Help' button is blocking the dragging of the right scrollbar, please optimize
![image](https://user-images.githubusercontent.com/121855031/218369746-ff2656ef-83bf-43dc-b9dd-4b62ec4e97ac.png)

**Comment by ydpzg** [comment]
We changed the position of the help icon on the making a chart page to the bottom right
