### ISSUE TITLE
Make up the continuity of these two token_slugs

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#418]
**Describe the bug**
 token_slug in ( 'ix-ixt' ,'weth')
**To Reproduce**
```
select * from token_daily_stats where token_slug ='ix-ixt'
-- weth
```
**Screenshots**
![image](https://user-images.githubusercontent.com/44665855/218395099-b32b740b-8718-4df5-9f5a-672d15617c77.png)

**Comment by Jakin-Liu** [comment]
We have fixed the data continuity problem of this token. If there are other problems, please contact us and thank you for your feedback
