### ISSUE TITLE
footprint can't open any table at 2:30pm

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#440]
**Describe the bug**

**To Reproduce**

**Screenshots**
I
![image](https://user-images.githubusercontent.com/44665855/220508534-819e41f7-a5e4-4dc1-8567-19c95ad4de5d.png)

![image](https://user-images.githubusercontent.com/44665855/220507995-d899d366-92fd-4413-9ca0-11b95e7ee40d.png)

**Comment by ydpzg** [comment]
The system is working. We will continue to optimize the stability of the system.
