### ISSUE TITLE
More transparency on contract submission statuses

### ISSUE THREAD

**Issue by bgodlin** [footprintanalytics/footprint-web#582]
**Is your feature request related to a problem? Please describe.**
Once user submits a contract decoding request, the following one will see it on https://www.footprint.network/submit/contract. Nevertheless, the statuses don't reflect the exact status of the submitted data: it's not clear whether data is yet only in `comm_{chain}_decoded_events` or already was copied to `{chain}_decoded_events`.

**Describe the solution you'd like**
More transparent statuses for the users.

**Describe alternatives you've considered**
-

**How important is this feature to you?**
Not really important, but would be a great enhancement

**Comment by ydpzg** [comment]
We have added a user guide on the page for this feature to make it easier for users. If there are any further questions, please raise an issue.
