### ISSUE TITLE
when download csv return error

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#596]
dashboard [link](https://www.footprint.network/@Shelly/Ronin-Chain-Ecosystem-Overview-Previous-365-Days?chain=Ronin&date_filter=past365days~)

![iShot_2023-04-07_19 03 27](https://user-images.githubusercontent.com/44665855/230598339-2d3de220-1483-4bf0-a06d-b815bea856e8.gif)

**Comment by ydpzg** [comment]
It has been fixed and the charts in the dashboard can be downloaded as data properly.
