### ISSUE TITLE
Ethereum bronze table missing 

### ISSUE THREAD

**Issue by sefigi** [footprintanalytics/footprint-web#746]
![image](https://github.com/footprintanalytics/footprint-web/assets/44665855/191fa41b-c56f-4b9e-bdb0-7c907ddf156b)

**Comment by meicanhong** [comment]
The footprint cannot use the underlying data of the eth chain and has been fixed.
reason:
Migrating doris missed some data. FP's view has used missing data, resulting in query not exist
solve:
Change FP view. Pure use of data under Iceberg
Subsequent replenishment Migration of data missed by doris.
Influence:
After the solution is completed, there will be no impact on the user
